name: LPC1768 LED Blink Build Check
on:
  push:
    branches: [ master, main ]
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'
jobs:
  call-build:
    uses: sirishakallam1991-ux/lpc1768-workflows/.github/workflows/reusable-build.yml@main
    with:
      project_name: "LPC1768 LED Blink"
    secrets:
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
